import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram } from "@solana/web3.js";
import { assert } from "chai";

describe("zk-verifier", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // @ts-ignore - IDL type will be generated by Anchor build
  const program = anchor.workspace.ZkVerifier as Program;

  const authority = provider.wallet;
  const holder = Keypair.generate();
  const issuerKeypair = Keypair.generate();

  let verifierStatePda: PublicKey;
  let issuerAccountPda: PublicKey;
  let credentialPda: PublicKey;

  const commitment = Array.from({ length: 32 }, (_, i) => i + 1) as number[];
  const verificationKey = Array.from({ length: 32 }, () => 0) as number[];

  before(async () => {
    [verifierStatePda] = PublicKey.findProgramAddressSync(
      [Buffer.from("verifier_state")],
      program.programId
    );

    [issuerAccountPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("issuer"), issuerKeypair.publicKey.toBuffer()],
      program.programId
    );

    [credentialPda] = PublicKey.findProgramAddressSync(
      [
        Buffer.from("credential"),
        holder.publicKey.toBuffer(),
        Buffer.from(commitment),
      ],
      program.programId
    );
  });

  it("Initializes the verifier", async () => {
    await program.methods
      .initializeVerifier(verificationKey)
      .accounts({
        verifierState: verifierStatePda,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    const state = await program.account.verifierState.fetch(verifierStatePda);
    assert.equal(state.authority.toBase58(), authority.publicKey.toBase58());
    assert.equal(state.totalVerifications.toNumber(), 0);
  });

  it("Registers an issuer", async () => {
    await program.methods
      .registerIssuer("Test Issuer", issuerKeypair.publicKey)
      .accounts({
        issuerAccount: issuerAccountPda,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    const issuer = await program.account.issuerAccount.fetch(issuerAccountPda);
    assert.equal(issuer.name, "Test Issuer");
    assert.equal(issuer.trusted, true);
    assert.equal(issuer.credentialsIssued.toNumber(), 0);
  });

  it("Issues a credential", async () => {
    const expiresAt = new anchor.BN(
      Math.floor(Date.now() / 1000) + 365 * 24 * 3600
    );

    await program.methods
      .issueCredential("age_verification", commitment, expiresAt)
      .accounts({
        credentialRecord: credentialPda,
        issuerAccount: issuerAccountPda,
        holder: holder.publicKey,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    const credential =
      await program.account.credentialRecord.fetch(credentialPda);
    assert.equal(credential.credentialType, "age_verification");
    assert.equal(credential.revoked, false);
    assert.deepEqual(credential.commitment, commitment);
  });

  it("Verifies a proof", async () => {
    const proofA = Array.from({ length: 64 }, (_, i) => i + 1);
    const proofB = Array.from({ length: 128 }, (_, i) => i + 1);
    const proofC = Array.from({ length: 64 }, (_, i) => i + 1);
    const publicSignals = [1, 0, 0, 0, 18, 0, 0, 0];

    const [verificationPda] = PublicKey.findProgramAddressSync(
      [
        Buffer.from("verification"),
        credentialPda.toBuffer(),
        authority.publicKey.toBuffer(),
      ],
      program.programId
    );

    const result = await program.methods
      .verifyProof(proofA, proofB, proofC, publicSignals)
      .accounts({
        verifierState: verifierStatePda,
        credentialRecord: credentialPda,
        verificationRecord: verificationPda,
        verifier: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    assert.ok(result);
  });

  it("Revokes a credential", async () => {
    await program.methods
      .revokeCredential()
      .accounts({
        credentialRecord: credentialPda,
        issuerAccount: issuerAccountPda,
        authority: authority.publicKey,
      })
      .rpc();

    const credential =
      await program.account.credentialRecord.fetch(credentialPda);
    assert.equal(credential.revoked, true);
  });

  it("Fails to verify a revoked credential", async () => {
    const proofA = Array.from({ length: 64 }, (_, i) => i + 1);
    const proofB = Array.from({ length: 128 }, (_, i) => i + 1);
    const proofC = Array.from({ length: 64 }, (_, i) => i + 1);
    const publicSignals = [1, 0, 0, 0, 18, 0, 0, 0];

    const [verificationPda2] = PublicKey.findProgramAddressSync(
      [
        Buffer.from("verification"),
        credentialPda.toBuffer(),
        holder.publicKey.toBuffer(),
      ],
      program.programId
    );

    try {
      await program.methods
        .verifyProof(proofA, proofB, proofC, publicSignals)
        .accounts({
          verifierState: verifierStatePda,
          credentialRecord: credentialPda,
          verificationRecord: verificationPda2,
          verifier: authority.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();
      assert.fail("Expected error for revoked credential");
    } catch (err: unknown) {
      assert.include((err as Error).message, "CredentialRevoked");
    }
  });
});
