"use client";

import { useState } from "react";
import { VerificationResult } from "@/components/VerificationResult";
import { verifyProof } from "@/lib/api";
import type { VerificationResult as VR, ZKProof, CredentialType } from "@/types";

export default function VerifyPage() {
  const [credentialId, setCredentialId] = useState("");
  const [circuitType, setCircuitType] = useState<CredentialType>("age_verification");
  const [proofJson, setProofJson] = useState("");
  const [signalsJson, setSignalsJson] = useState("");
  const [verifierKey, setVerifierKey] = useState("");
  const [result, setResult] = useState<VR | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleVerify = async () => {
    setError(null);
    setResult(null);
    setLoading(true);
    try {
      const proof = JSON.parse(proofJson) as ZKProof;
      const publicSignals = JSON.parse(signalsJson) as string[];
      const res = await verifyProof({
        credentialId,
        circuitType,
        proof,
        publicSignals,
        verifierPublicKey: verifierKey,
      });
      setResult(res);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Verification failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen pt-24 px-4">
      <div className="max-w-2xl mx-auto">
        <h1 className="text-4xl font-bold mb-2">Verify a Credential</h1>
        <p className="text-slate-400 mb-10">
          Submit a ZK proof for on-chain verification. Paste the proof
          artifacts generated by the holder.
        </p>

        <div className="glass rounded-2xl p-6 space-y-4">
          <div>
            <label className="block text-sm font-medium text-slate-300 mb-1">
              Credential ID
            </label>
            <input
              value={credentialId}
              onChange={(e) => setCredentialId(e.target.value)}
              placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
              className="w-full px-4 py-2 rounded-lg bg-slate-800 border border-slate-700 focus:border-brand-500 outline-none text-sm"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-300 mb-1">
              Circuit Type
            </label>
            <select
              value={circuitType}
              onChange={(e) => setCircuitType(e.target.value as CredentialType)}
              className="w-full px-4 py-2 rounded-lg bg-slate-800 border border-slate-700 focus:border-brand-500 outline-none text-sm"
            >
              <option value="age_verification">Age Verification</option>
              <option value="citizenship">Citizenship</option>
              <option value="income">Income Verification</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-300 mb-1">
              Proof JSON
            </label>
            <textarea
              value={proofJson}
              onChange={(e) => setProofJson(e.target.value)}
              rows={6}
              placeholder='{"pi_a": [...], "pi_b": [...], "pi_c": [...], ...}'
              className="w-full px-4 py-2 rounded-lg bg-slate-800 border border-slate-700 focus:border-brand-500 outline-none text-sm font-mono"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-300 mb-1">
              Public Signals JSON
            </label>
            <input
              value={signalsJson}
              onChange={(e) => setSignalsJson(e.target.value)}
              placeholder='["1", "0", "18"]'
              className="w-full px-4 py-2 rounded-lg bg-slate-800 border border-slate-700 focus:border-brand-500 outline-none text-sm font-mono"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-300 mb-1">
              Your Wallet Public Key
            </label>
            <input
              value={verifierKey}
              onChange={(e) => setVerifierKey(e.target.value)}
              placeholder="44-character Solana public key"
              className="w-full px-4 py-2 rounded-lg bg-slate-800 border border-slate-700 focus:border-brand-500 outline-none text-sm"
            />
          </div>

          {error && (
            <p className="text-red-400 text-sm">{error}</p>
          )}

          <button
            onClick={handleVerify}
            disabled={loading}
            className="w-full py-3 rounded-xl bg-brand-600 hover:bg-brand-500 disabled:opacity-50 font-semibold transition-colors"
          >
            {loading ? "Verifying…" : "Verify Proof"}
          </button>
        </div>

        {result && (
          <div className="mt-8">
            <VerificationResult result={result} />
          </div>
        )}
      </div>
    </div>
  );
}
